### ISSUE TITLE
Get /user return 500 Internal Server Error 

### ISSUE THREAD

**Issue by Lobynya** [TheChance101/beep-beep#549]
Hello!

After login, when client app do request 

@GET https://beep-beep-api-gateway-nap2u.ondigitalocean.app/user

server return 500 Internal Server Error 

For example user "test", password "Qwerty123!"

**Comment by AzizaHelmy** [comment]
please follow this issue :
https://github.com/TheChance101/beep-beep/issues/551#issuecomment-1798531053
and let me know if your problem is solved

**Comment by Lobynya** [comment]
I try to login in client_end_user app

I check user "test" in dashboard app, he has permission "End User"

But, request 

curl --location 'https://beep-beep-api-gateway-nap2u.ondigitalocean.app/user' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhbGxfdXNlcnMiLCJpc3MiOiJ0aGUtY2hhbmNlLm9yZyIsInBlcm1pc3Npb24iOiI2MyIsImV4cCI6MTczMDE3Mjk0MCwidG9rZW5UeXBlIjoiQUNDRVNTX1RPS0VOIiwidXNlcklkIjoiNjU0OWM3Y2UwYjEyNzg2ODZiODU2ODZhIiwidXNlcm5hbWUiOiJ0ZXN0In0.u9EVkL2PEP7oYFxDleZjD6Gxa5WG7nFSm3NhXU-LuaU'

still return error code 500 

If I create new user - it still return code 500
