### ISSUE TITLE
Login into apps

### ISSUE THREAD

**Issue by RaheemJnr** [TheChance101/beep-beep#551]
how do i login on the app after building on my local device

**Comment by AzizaHelmy** [comment]
@RaheemJnr 
which app you need to login in?

**Comment by RaheemJnr** [comment]
The taxi and delivery app. And shouldn't we be able to login to all the app

**Comment by AzizaHelmy** [comment]
@RaheemJnr 
yes you can  login to all the app, but for dashboard,taxi ,delivery and restaurant apps you need first to create an account via The main app (Beep Beep app) then you can login to these apps
also to access these  apps you need to get the permission from the Admain first (via dashboard app) .
for now you can test to login use these account it has the permissions for all the apps :

username: ahmed_nasser
password: 12345678aA@

**Comment by RaheemJnr** [comment]
alright thank you
