### ISSUE TITLE
The Desktop Client App can't connect to the internet

### ISSUE THREAD

**Issue by RaheemJnr** [TheChance101/beep-beep#628]
i keep getting "No internet connection" when i try to login on desktop, even after i bypass the failed state check in the code i still keep getting no internet connection 
![image](https://github.com/TheChance101/beep-beep/assets/66214213/643042ab-13b6-43b2-ba89-7971ec83dd3f)

**Comment by RaheemJnr** [comment]
i think the question i should ask is how do i set up the api_gateway locally @ahmednasserzaza or anybody else that can help

**Comment by muhammadzkralla** [comment]
To run the api_getway locally, you should open the api_gateway module and navigate to the Application.kt file and run the main function.

Application.kt :
https://github.com/TheChance101/beep-beep/blob/develop/api_gateway%2Fsrc%2Fmain%2Fkotlin%2Forg%2Fthechance%2Fapi_gateway%2FApplication.kt


This will host the ktor server project on your localhost and the ip address of your machine.

Note:
If you are using the virtual phone emulator or your physical phone or any external device that's not the machine you ran the Application.kt file on, you will need to put the ip address of your running machine as the base url and not **localhost** to access the api.

You can get the ip address of your machine by opening the cmd and typing the ipconfig command.

@RaheemJnr

**Comment by RaheemJnr** [comment]
Do i need to start all the other microservices???

**Comment by muhammadzkralla** [comment]
The api_gateway module receives requests, forwards them to the responsible microservice, takes its response, and returns it to the client. Therefore, you will need to run the other microservices as well. Be aware of the URLs of each microservice, which you can find in the [APIS.kt](https://github.com/TheChance101/beep-beep/blob/develop/api_gateway/src/main/kotlin/org/thechance/api_gateway/util/APIs.kt "APIS.kt]") file.

**Comment by RaheemJnr** [comment]
Alright thank you
